/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReciclagemRouteImport } from './routes/reciclagem'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EncontrarCatadoresRouteImport } from './routes/encontrar-catadores'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PontoIdRouteImport } from './routes/ponto.$id'
import { Route as ConfirmacaoIdRouteImport } from './routes/confirmacao.$id'
import { Route as AgendarIdRouteImport } from './routes/agendar.$id'

const ReciclagemRoute = ReciclagemRouteImport.update({
  id: '/reciclagem',
  path: '/reciclagem',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EncontrarCatadoresRoute = EncontrarCatadoresRouteImport.update({
  id: '/encontrar-catadores',
  path: '/encontrar-catadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoIdRoute = PontoIdRouteImport.update({
  id: '/ponto/$id',
  path: '/ponto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoIdRoute = ConfirmacaoIdRouteImport.update({
  id: '/confirmacao/$id',
  path: '/confirmacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarIdRoute = AgendarIdRouteImport.update({
  id: '/agendar/$id',
  path: '/agendar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/ajuda': typeof AjudaRoute
  '/encontrar-catadores': typeof EncontrarCatadoresRoute
  '/home': typeof HomeRoute
  '/mapa': typeof MapaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/reciclagem': typeof ReciclagemRoute
  '/agendar/$id': typeof AgendarIdRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/ponto/$id': typeof PontoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/ajuda': typeof AjudaRoute
  '/encontrar-catadores': typeof EncontrarCatadoresRoute
  '/home': typeof HomeRoute
  '/mapa': typeof MapaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/reciclagem': typeof ReciclagemRoute
  '/agendar/$id': typeof AgendarIdRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/ponto/$id': typeof PontoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/ajuda': typeof AjudaRoute
  '/encontrar-catadores': typeof EncontrarCatadoresRoute
  '/home': typeof HomeRoute
  '/mapa': typeof MapaRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/reciclagem': typeof ReciclagemRoute
  '/agendar/$id': typeof AgendarIdRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/ponto/$id': typeof PontoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamentos'
    | '/ajuda'
    | '/encontrar-catadores'
    | '/home'
    | '/mapa'
    | '/notificacoes'
    | '/perfil'
    | '/reciclagem'
    | '/agendar/$id'
    | '/confirmacao/$id'
    | '/ponto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/ajuda'
    | '/encontrar-catadores'
    | '/home'
    | '/mapa'
    | '/notificacoes'
    | '/perfil'
    | '/reciclagem'
    | '/agendar/$id'
    | '/confirmacao/$id'
    | '/ponto/$id'
  id:
    | '__root__'
    | '/'
    | '/agendamentos'
    | '/ajuda'
    | '/encontrar-catadores'
    | '/home'
    | '/mapa'
    | '/notificacoes'
    | '/perfil'
    | '/reciclagem'
    | '/agendar/$id'
    | '/confirmacao/$id'
    | '/ponto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentosRoute: typeof AgendamentosRoute
  AjudaRoute: typeof AjudaRoute
  EncontrarCatadoresRoute: typeof EncontrarCatadoresRoute
  HomeRoute: typeof HomeRoute
  MapaRoute: typeof MapaRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRoute
  ReciclagemRoute: typeof ReciclagemRoute
  AgendarIdRoute: typeof AgendarIdRoute
  ConfirmacaoIdRoute: typeof ConfirmacaoIdRoute
  PontoIdRoute: typeof PontoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reciclagem': {
      id: '/reciclagem'
      path: '/reciclagem'
      fullPath: '/reciclagem'
      preLoaderRoute: typeof ReciclagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encontrar-catadores': {
      id: '/encontrar-catadores'
      path: '/encontrar-catadores'
      fullPath: '/encontrar-catadores'
      preLoaderRoute: typeof EncontrarCatadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/$id': {
      id: '/ponto/$id'
      path: '/ponto/$id'
      fullPath: '/ponto/$id'
      preLoaderRoute: typeof PontoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao/$id': {
      id: '/confirmacao/$id'
      path: '/confirmacao/$id'
      fullPath: '/confirmacao/$id'
      preLoaderRoute: typeof ConfirmacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$id': {
      id: '/agendar/$id'
      path: '/agendar/$id'
      fullPath: '/agendar/$id'
      preLoaderRoute: typeof AgendarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentosRoute: AgendamentosRoute,
  AjudaRoute: AjudaRoute,
  EncontrarCatadoresRoute: EncontrarCatadoresRoute,
  HomeRoute: HomeRoute,
  MapaRoute: MapaRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRoute,
  ReciclagemRoute: ReciclagemRoute,
  AgendarIdRoute: AgendarIdRoute,
  ConfirmacaoIdRoute: ConfirmacaoIdRoute,
  PontoIdRoute: PontoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
